alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
name: n8n-app-do
envs:
  - key: DB_TYPE
    value: postgresdb
  - key: DB_POSTGRESDB_DATABASE
    value: ${DATABASE}
  - key: DB_POSTGRESDB_HOST
    value: ${HOSTNAME}
  - key: DB_POSTGRESDB_PORT
    value: ${PORT}
  - key: DB_POSTGRESDB_USER
    value: ${USERNAME}
  - key: DB_POSTGRESDB_PASSWORD
    value: ${PASSWORD}
services:
  - name: n8n-app-do
    build_command: npm install
    environment_slug: node-js
    envs:
      - key: N8N_BASIC_AUTH_ACTIVE
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: N8N_BASIC_AUTH_USER
        scope: RUN_AND_BUILD_TIME
        value: ht-user
      - key: N8N_BASIC_AUTH_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "Ch@ngeMe!"
      - key: WEBHOOK_URL
        scope: RUN_AND_BUILD_TIME
        value: ${_self.PUBLIC_URL}
    git:
      branch: master
      repo_clone_url: https://github.com/johnkraczek/n8n-app-do.git
    http_port: 5678
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    run_command: ./node_modules/n8n/bin/n8n
databases:
  - name: "n8n-db"
    engine: PG
    production: false
