name: n8n-app-do
services:
- environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: johnkraczek/n8n-app-do
  name: n8n-app-do
  envs:
    - key: N8N_BASIC_AUTH_ACTIVE
      value: false
    - key: N8N_BASIC_AUTH_USER
      value: 'ht-user'
    - key: N8N_BASIC_AUTH_PASSWORD
      value: 'Ch@ngeMe!'
    - key: WEBHOOK_URL
      value: ${PUBLIC_URL}